<?php $funres=$this->ShowCustomRecords(); ?>

<?php $result = $funres->fetchAll(); ?>
<table cellspacing="0" class="data-table" id="data-table">
            <tr>
            <th><?php echo $this->__('Id') ?></th>
            <th><?php echo $this->__('pic') ?></th>
            <th><?php echo $this->__('name') ?></th>
            <th><?php echo $this->__('message') ?></th>
        </tr>
  <?php
foreach($result as $values)
{
echo '<tr>';
echo '<td>'.$values['id'].'</td>';
echo '<td>'.$values['pic'].'</td>';
echo '<td>'.$values['name'].'</td>'; 
echo '<td>'.$values['message'].'</td>'; 
echo '</tr>';
} 
?>
</table>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_datasets = $this->getDatasets(); ?>
<div class="page-head">
    <h3><?php echo $this->__('Testimonials') ?></h3>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php // if($_datasets->getSize()): ?>
<table cellspacing="0" class="data-table" id="data-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Id') ?></th>
            
            <th><?php echo $this->__('pic') ?></th>
            <th><?php echo $this->__('name') ?></th>
            <th><?php echo $this->__('message') ?></th>
            <th> &nbsp; </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_datasets as $_dataset): ?>
            <tr>
                <td  valign="middle"   style="vertical-align:middle;"><?php echo $_dataset->getId() ?></td>
                
            <td  valign="middle"   style="vertical-align:middle;"><?php echo $_dataset->getData('pic') ?></td>
            <td  valign="middle"   style="vertical-align:middle;"><?php echo $_dataset->getData('name') ?></td>
            <td  valign="middle"   style="vertical-align:middle;"><?php echo $_dataset->getData('message') ?></td>
				<td  valign="middle"   style="vertical-align:middle;"><a href="#" ><?php echo($this->__('View')) ?></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('data-table')</script>
<?php echo $this->getPagerHtml(); ?>
<?php // else: ?>
    <p><?php // echo $this->__('You have submited no data.'); ?></p>
<?php // endif ?>
